# Generated by Django 4.0.5 on 2022-06-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbers',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='barbers',
            old_name='Surname',
            new_name='surname',
        ),
    ]
