# Generated by Django 4.0.5 on 2022-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_rename_name_barbers_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('validity', models.BooleanField(default=False)),
            ],
        ),
    ]
