# Generated by Django 4.0.5 on 2022-06-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_availabletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='available_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barbers.availabletime'),
        ),
    ]
